<?xml version="1.0" encoding="utf-8"?><Database Name="PeopleDB" Class="PeopleDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Employee_Expense" Member="Expenses" ThisKey="ID" OtherKey="Employee_ID" Type="Expense" />
    </Type>
  </Table>
  <Table Name="dbo.Expenses" Member="Expenses">
    <Type Name="Expense">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ExpenseType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Employee_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Employee_Expense" Member="Employee" ThisKey="Employee_ID" OtherKey="ID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
</Database>